# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ['--unsafe']
      - id: check-added-large-files
        args: ['--maxkb=600']
      - id: check-toml
      - id: check-json
      - id: check-symlinks
      - id: detect-private-key
  - repo: https://github.com/psf/black
    rev: '23.3.0'
    hooks:
      - id: black
  - repo: https://github.com/adamchainz/blacken-docs
    rev: "1.14.0"
    hooks:
      - id: blacken-docs
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.275'
    hooks:
      - id: ruff
        args: [--fix]
  - repo: https://github.com/python-poetry/poetry
    rev: '1.5.0'
    hooks:
      - id: poetry-check
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.23.2
    hooks:
      - id: check-github-workflows
