# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ['--unsafe']
      - id: check-added-large-files
        args: ['--maxkb=600']
  - repo: https://github.com/pycqa/isort
    rev: '5.11.5'
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]
      - id: isort
        name: isort (cython)
        types: [cython]
        args: ["--profile", "black"]
      - id: isort
        name: isort (pyi)
        types: [pyi]
        args: ["--profile", "black"]

  - repo: https://github.com/psf/black
    rev: '23.1.0'
    hooks:
      - id: black
  - repo: https://github.com/adamchainz/blacken-docs
    rev: "v1.12.1"
    hooks:
      - id: blacken-docs
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.241'
    hooks:
      - id: ruff
  - repo: https://github.com/python-poetry/poetry
    rev: '1.3.0'
    hooks:
      - id: poetry-check
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.21.0
    hooks:
      - id: check-github-workflows
